import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
    NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
    APP_NAME: Joi.string().default('backend'),
    PORT: Joi.number().port().default(3000),
    FRONTEND_URL: Joi.string().uri().required(),
    ENABLE_HIBP_CHECK: Joi.boolean().default(false),
    ENABLE_COMMON_PASSWORD_CHECK: Joi.boolean().default(false),
    DATABASE_URL: Joi.string().uri().required(),
    REDIS_URL: Joi.string().uri().required(),
    THROTTLE_DEFAULT_TTL: Joi.number().integer().positive().required(),
    THROTTLE_DEFAULT_LIMIT: Joi.number().integer().positive().required(),
    THROTTLE_AUTH_TTL: Joi.number().integer().positive().required(),
    THROTTLE_AUTH_LIMIT: Joi.number().integer().positive().required(),
    THROTTLE_OTP_TTL: Joi.number().integer().positive().required(),
    THROTTLE_OTP_LIMIT: Joi.number().integer().positive().required(),
    // Email Configuration
    MAIL_HOST: Joi.string().when('EMAIL_PROVIDER', { is: 'smtp', then: Joi.required(), otherwise: Joi.optional() }),
    MAIL_PORT: Joi.number().default(1025),
    MAIL_USER: Joi.string().allow('').optional(),
    MAIL_PASS: Joi.string().allow('').optional(),
    MAIL_FROM: Joi.string().required(),
    MAIL_SECURE: Joi.boolean().default(false),
    MAIL_VERIFICATION_TOKEN_TTL: Joi.number().required().integer().positive(),
    EMAIL_PROVIDER: Joi.string().valid('smtp', 'resend').required().default('smtp'),
    RESEND_API_KEY: Joi.string().when('EMAIL_PROVIDER', { is: 'resend', then: Joi.required(), otherwise: Joi.optional().allow('') }),
    MAIL_POOL: Joi.boolean().default(true).required(),
    MAIL_MAX_CONNECTIONS: Joi.number().integer().positive().required().default(5),
    MAIL_MAX_MESSAGES: Joi.number().integer().positive().required().default(100),
    MAIL_CONNECTION_TIMEOUT: Joi.number().integer().positive().required().default(10000),
    MAIL_GREETING_TIMEOUT: Joi.number().integer().positive().required().default(10000),
    MAIL_SOCKET_TIMEOUT: Joi.number().integer().positive().required().default(30000),
    MAIL_QUEUE_CONCURRENCY: Joi.number().integer().positive().required().default(5),
    MAIL_QUEUE_RATE_LIMIT_MAX: Joi.number().integer().positive().required().default(50),
    MAIL_QUEUE_RATE_LIMIT_DURATION: Joi.number().integer().positive().required().default(1000),
})